# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'ZJTableViewManager', '~> 0.0.9'
    pod 'SwiftyStarRatingView'
    pod 'ImagePicker'
    pod 'SKPhotoBrowser', '~> 5.0.0'
    pod 'IQKeyboardManagerSwift'
  # Pods for Demos

end
